model:
    arch: icnet
data:
    dataset: custom
    train_split: train
    val_split: val
    img_rows: 512
    img_cols: 512
    path: /private/home/meetshah/misc_code/ps/data/VOCdevkit/VOC2012/
training:
    train_iters: 300000
    batch_size: 5
    val_interval: 500
    print_interval: 25
    optimizer:
        name: 'sgd'
        lr: 1.0e-10
        weight_decay: 0.0005
        momentum: 0.99
    augmentations:
        rcrop: [512, 512]
    l_schedule: poly_lr
    resume: icnet_custom_best_model.pkl
    visdom: False



